version: 2
jobs:
  build:
    working_directory: ~/dorm_elect
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Update Container
          command: apt-get update
      - run:
          name: Hotfix to container
          command: apt-get install -y ca-certificates curl sudo
      - checkout
      - run:
          name: Install NodeJS
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            apt-get install nodejs
            apt-get install build-essential
      - run:
          name: Install NPM modules
          command: |
            npm install syntax-checker -g
            npm install uglifyjs -g
      - run:
          name: Test Files
          command: syntax-checker ~/dorm_elect
      - store_artifacts:
          path: /root/dorm_elect
