version: 2
jobs:
  build:
    working_directory: ~/dorm_elect
    docker:
      - image: centos:centos6.9
    steps:
      - checkout
      - run:
          name: Update Container
          command: yum update -y
      - run:
          name: Hotfix to container
          command: yum install -y ca-certificates curl sudo
      - run:
          name: Install Required complier
          command: yum install -y uglifyjs zip unzip git epel-release wget tar gcc gcc+ make
      - run:
          name: Install PHP 
          command: yum install -y php php-curl php-xml php-ldap php-cli php-common php-mysql
      - run:
          name: Check PHP version
          command: php -v
      - run:
          name: Download and extract NodeJS
          command: |
            mkdir ~/nodejs
            cd ~/nodejs
            wget https://nodejs.org/download/release/v9.3.0/node-v9.3.0-linux-s390x.tar.gz
            tar xzvf node-v9.3.0-linux-s390x.tar.gz && cd node-v9.3.0-linux-s390x
      - run:
          name: Make NodeJS
          command: |
            ./configure
            make
            make install
      - run:
          name: Check NodeJS version
          command: |
            node --version
            cd ~/dorm_elect
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: composer
          command: |
            php composer.phar require --dev jakub-onderka/php-parallel-lint
            php composer.phar require --dev jakub-onderka/php-console-highlighter
      - run:
          name: Test Files
          command: ./vendor/bin/parallel-lint .
      - store_artifacts:
          path: /root/dorm_elect